name: CozyBrew
options:
  bundleIdPrefix: com.s2j
  deploymentTarget:
    macOS: "12.0"
  developmentLanguage: en
  xcodeVersion: "15.0"
  usesTabs: false
  indentWidth: 4
  tabWidth: 4

packages:
  s2j-source-list:
    url: https://github.com/stein2nd/s2j-source-list.git
    branch: main
  s2j-about-window:
    url: https://github.com/stein2nd/s2j-about-window.git
    branch: main

targets:
  CozyBrewApp:
    type: application
    platform: macOS
    deploymentTarget: "12.0"
    sources:
      - path: CozyBrewApp
    resources:
      - path: CozyBrewApp/Assets.xcassets
    info:
      path: CozyBrewApp/Info.plist
      properties:
        CFBundleDevelopmentRegion: en
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: 1
        LSMinimumSystemVersion: "12.0"
        NSHumanReadableCopyright: "Copyright © 2024 S2J. All rights reserved."
        NSPrincipalClass: NSApplication
        NSHighResolutionCapable: true
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
    entitlements:
      path: CozyBrewApp/CozyBrewApp.entitlements
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.s2j.CozyBrew
      PRODUCT_NAME: CozyBrew
      SWIFT_VERSION: "5.9"
      MACOSX_DEPLOYMENT_TARGET: "12.0"
      CODE_SIGN_ENTITLEMENTS: CozyBrewApp/CozyBrewApp.entitlements
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ""
      ENABLE_HARDENED_RUNTIME: true
      ENABLE_APP_SANDBOX: false
      SWIFT_PACKAGE_DEPENDENCIES: "$(SRCROOT)/Package.swift"
    dependencies:
      - target: CozyBrewCore
      - target: CozyBrewService
      - target: CozyBrewUIComponents
      - package: s2j-source-list
        product: S2JSourceList
      - package: s2j-about-window
        product: S2JAboutWindow
      - sdk: SwiftUI.framework
      - sdk: Combine.framework

  CozyBrewCore:
    type: framework
    platform: macOS
    deploymentTarget: "12.0"
    sources:
      - path: Sources/CozyBrewCore
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.s2j.CozyBrewCore
      PRODUCT_NAME: CozyBrewCore
      SWIFT_VERSION: "5.9"
      MACOSX_DEPLOYMENT_TARGET: "12.0"
      DEFINES_MODULE: true

  CozyBrewService:
    type: framework
    platform: macOS
    deploymentTarget: "12.0"
    sources:
      - path: Sources/CozyBrewService
    dependencies:
      - target: CozyBrewCore
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.s2j.CozyBrewService
      PRODUCT_NAME: CozyBrewService
      SWIFT_VERSION: "5.9"
      MACOSX_DEPLOYMENT_TARGET: "12.0"
      DEFINES_MODULE: true

  CozyBrewUIComponents:
    type: framework
    platform: macOS
    deploymentTarget: "12.0"
    sources:
      - path: Sources/CozyBrewUIComponents
    dependencies:
      - target: CozyBrewService
      - package: s2j-source-list
        product: S2JSourceList
      - package: s2j-about-window
        product: S2JAboutWindow
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.s2j.CozyBrewUIComponents
      PRODUCT_NAME: CozyBrewUIComponents
      SWIFT_VERSION: "5.9"
      MACOSX_DEPLOYMENT_TARGET: "12.0"
      DEFINES_MODULE: true

schemes:
  CozyBrewApp:
    build:
      targets:
        CozyBrewApp: all
        CozyBrewCore: all
        CozyBrewService: all
        CozyBrewUIComponents: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - CozyBrewCoreTests
        - CozyBrewServiceTests
